//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Backend.CAFFParser {

class CAFFParserPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="SWIGRegisterExceptionCallbacks_CAFFParser")]
    public static extern void SWIGRegisterExceptionCallbacks_CAFFParser(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_CAFFParser")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_CAFFParser(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_CAFFParser(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_CAFFParser(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="SWIGRegisterStringCallback_CAFFParser")]
    public static extern void SWIGRegisterStringCallback_CAFFParser(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_CAFFParser(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static CAFFParserPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFF_parseCIFF___")]
  public static extern global::System.IntPtr CIFF_parseCIFF(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFF_getHeaderSize___")]
  public static extern long CIFF_getHeaderSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFF_getContentSize___")]
  public static extern long CIFF_getContentSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFF_getImageWidth___")]
  public static extern long CIFF_getImageWidth(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFF_getImageHeight___")]
  public static extern long CIFF_getImageHeight(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFF_getCaption___")]
  public static extern string CIFF_getCaption(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFF_getTags___")]
  public static extern global::System.IntPtr CIFF_getTags(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFF_getPixels___")]
  public static extern global::System.IntPtr CIFF_getPixels(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFF_isValid___")]
  public static extern bool CIFF_isValid(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFF_getParseFails___")]
  public static extern global::System.IntPtr CIFF_getParseFails(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_delete_CIFF___")]
  public static extern void delete_CIFF(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_DateTime_year_set___")]
  public static extern void DateTime_year_set(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_DateTime_year_get___")]
  public static extern ushort DateTime_year_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_DateTime_month_set___")]
  public static extern void DateTime_month_set(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_DateTime_month_get___")]
  public static extern byte DateTime_month_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_DateTime_day_set___")]
  public static extern void DateTime_day_set(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_DateTime_day_get___")]
  public static extern byte DateTime_day_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_DateTime_hour_set___")]
  public static extern void DateTime_hour_set(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_DateTime_hour_get___")]
  public static extern byte DateTime_hour_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_DateTime_minute_set___")]
  public static extern void DateTime_minute_set(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_DateTime_minute_get___")]
  public static extern byte DateTime_minute_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_new_DateTime___")]
  public static extern global::System.IntPtr new_DateTime();

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_delete_DateTime___")]
  public static extern void delete_DateTime(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CAFF_parseCAFF___")]
  public static extern global::System.IntPtr CAFF_parseCAFF(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CAFF_getNumberOfAnimations___")]
  public static extern ulong CAFF_getNumberOfAnimations(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CAFF_getCreationDate___")]
  public static extern global::System.IntPtr CAFF_getCreationDate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CAFF_getCreator___")]
  public static extern string CAFF_getCreator(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CAFF_getCiffsWithDuration___")]
  public static extern global::System.IntPtr CAFF_getCiffsWithDuration(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CAFF_isValid___")]
  public static extern bool CAFF_isValid(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CAFF_generatePpmPreview___")]
  public static extern global::System.IntPtr CAFF_generatePpmPreview(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CAFF_generateMetaDataJson___")]
  public static extern string CAFF_generateMetaDataJson(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CAFF_getParseFails___")]
  public static extern global::System.IntPtr CAFF_getParseFails(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_delete_CAFF___")]
  public static extern void delete_CAFF(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_Clear___")]
  public static extern void BytesVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_Add___")]
  public static extern void BytesVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_size___")]
  public static extern uint BytesVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_capacity___")]
  public static extern uint BytesVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_reserve___")]
  public static extern void BytesVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_new_BytesVector__SWIG_0___")]
  public static extern global::System.IntPtr new_BytesVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_new_BytesVector__SWIG_1___")]
  public static extern global::System.IntPtr new_BytesVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_new_BytesVector__SWIG_2___")]
  public static extern global::System.IntPtr new_BytesVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_getitemcopy___")]
  public static extern byte BytesVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_getitem___")]
  public static extern byte BytesVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_setitem___")]
  public static extern void BytesVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, byte jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_AddRange___")]
  public static extern void BytesVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_GetRange___")]
  public static extern global::System.IntPtr BytesVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_Insert___")]
  public static extern void BytesVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, byte jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_InsertRange___")]
  public static extern void BytesVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_RemoveAt___")]
  public static extern void BytesVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_RemoveRange___")]
  public static extern void BytesVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_Repeat___")]
  public static extern global::System.IntPtr BytesVector_Repeat(byte jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_Reverse__SWIG_0___")]
  public static extern void BytesVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_Reverse__SWIG_1___")]
  public static extern void BytesVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_SetRange___")]
  public static extern void BytesVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_Contains___")]
  public static extern bool BytesVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_IndexOf___")]
  public static extern int BytesVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_LastIndexOf___")]
  public static extern int BytesVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_BytesVector_Remove___")]
  public static extern bool BytesVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_delete_BytesVector___")]
  public static extern void delete_BytesVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_Clear___")]
  public static extern void StringVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_Add___")]
  public static extern void StringVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_size___")]
  public static extern uint StringVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_capacity___")]
  public static extern uint StringVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_reserve___")]
  public static extern void StringVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_new_StringVector__SWIG_0___")]
  public static extern global::System.IntPtr new_StringVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_new_StringVector__SWIG_1___")]
  public static extern global::System.IntPtr new_StringVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_new_StringVector__SWIG_2___")]
  public static extern global::System.IntPtr new_StringVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_getitemcopy___")]
  public static extern string StringVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_getitem___")]
  public static extern string StringVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_setitem___")]
  public static extern void StringVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_AddRange___")]
  public static extern void StringVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_GetRange___")]
  public static extern global::System.IntPtr StringVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_Insert___")]
  public static extern void StringVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_InsertRange___")]
  public static extern void StringVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_RemoveAt___")]
  public static extern void StringVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_RemoveRange___")]
  public static extern void StringVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_Repeat___")]
  public static extern global::System.IntPtr StringVector_Repeat(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_Reverse__SWIG_0___")]
  public static extern void StringVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_Reverse__SWIG_1___")]
  public static extern void StringVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_SetRange___")]
  public static extern void StringVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_Contains___")]
  public static extern bool StringVector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_IndexOf___")]
  public static extern int StringVector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_LastIndexOf___")]
  public static extern int StringVector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_StringVector_Remove___")]
  public static extern bool StringVector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_delete_StringVector___")]
  public static extern void delete_StringVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_new_CIFFAndDuration__SWIG_0___")]
  public static extern global::System.IntPtr new_CIFFAndDuration__SWIG_0(long jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_new_CIFFAndDuration__SWIG_1___")]
  public static extern global::System.IntPtr new_CIFFAndDuration__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDuration_first_set___")]
  public static extern void CIFFAndDuration_first_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDuration_first_get___")]
  public static extern long CIFFAndDuration_first_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDuration_second_set___")]
  public static extern void CIFFAndDuration_second_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDuration_second_get___")]
  public static extern global::System.IntPtr CIFFAndDuration_second_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_delete_CIFFAndDuration___")]
  public static extern void delete_CIFFAndDuration(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_Clear___")]
  public static extern void CIFFAndDurationVector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_Add___")]
  public static extern void CIFFAndDurationVector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_size___")]
  public static extern uint CIFFAndDurationVector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_capacity___")]
  public static extern uint CIFFAndDurationVector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_reserve___")]
  public static extern void CIFFAndDurationVector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_new_CIFFAndDurationVector__SWIG_0___")]
  public static extern global::System.IntPtr new_CIFFAndDurationVector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_new_CIFFAndDurationVector__SWIG_1___")]
  public static extern global::System.IntPtr new_CIFFAndDurationVector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_new_CIFFAndDurationVector__SWIG_2___")]
  public static extern global::System.IntPtr new_CIFFAndDurationVector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_getitemcopy___")]
  public static extern global::System.IntPtr CIFFAndDurationVector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_getitem___")]
  public static extern global::System.IntPtr CIFFAndDurationVector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_setitem___")]
  public static extern void CIFFAndDurationVector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_AddRange___")]
  public static extern void CIFFAndDurationVector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_GetRange___")]
  public static extern global::System.IntPtr CIFFAndDurationVector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_Insert___")]
  public static extern void CIFFAndDurationVector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_InsertRange___")]
  public static extern void CIFFAndDurationVector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_RemoveAt___")]
  public static extern void CIFFAndDurationVector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_RemoveRange___")]
  public static extern void CIFFAndDurationVector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_Repeat___")]
  public static extern global::System.IntPtr CIFFAndDurationVector_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_Reverse__SWIG_0___")]
  public static extern void CIFFAndDurationVector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_Reverse__SWIG_1___")]
  public static extern void CIFFAndDurationVector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_CIFFAndDurationVector_SetRange___")]
  public static extern void CIFFAndDurationVector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("CAFFParser_lib", EntryPoint="CSharp_BackendfCAFFParser_delete_CIFFAndDurationVector___")]
  public static extern void delete_CIFFAndDurationVector(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
