//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Backend.CAFFParser {

public class CIFFAndDurationVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<CIFFAndDuration>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CIFFAndDurationVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CIFFAndDurationVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CIFFAndDurationVector obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CIFFAndDurationVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CAFFParserPINVOKE.delete_CIFFAndDurationVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CIFFAndDurationVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (CIFFAndDuration element in c) {
      this.Add(element);
    }
  }

  public CIFFAndDurationVector(global::System.Collections.Generic.IEnumerable<CIFFAndDuration> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (CIFFAndDuration element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public CIFFAndDuration this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(CIFFAndDuration[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(CIFFAndDuration[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, CIFFAndDuration[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public CIFFAndDuration[] ToArray() {
    CIFFAndDuration[] array = new CIFFAndDuration[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<CIFFAndDuration> global::System.Collections.Generic.IEnumerable<CIFFAndDuration>.GetEnumerator() {
    return new CIFFAndDurationVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new CIFFAndDurationVectorEnumerator(this);
  }

  public CIFFAndDurationVectorEnumerator GetEnumerator() {
    return new CIFFAndDurationVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class CIFFAndDurationVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<CIFFAndDuration>
  {
    private CIFFAndDurationVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public CIFFAndDurationVectorEnumerator(CIFFAndDurationVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public CIFFAndDuration Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (CIFFAndDuration)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    CAFFParserPINVOKE.CIFFAndDurationVector_Clear(swigCPtr);
  }

  public void Add(CIFFAndDuration x) {
    CAFFParserPINVOKE.CIFFAndDurationVector_Add(swigCPtr, CIFFAndDuration.getCPtr(x));
    if (CAFFParserPINVOKE.SWIGPendingException.Pending) throw CAFFParserPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = CAFFParserPINVOKE.CIFFAndDurationVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = CAFFParserPINVOKE.CIFFAndDurationVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    CAFFParserPINVOKE.CIFFAndDurationVector_reserve(swigCPtr, n);
  }

  public CIFFAndDurationVector() : this(CAFFParserPINVOKE.new_CIFFAndDurationVector__SWIG_0(), true) {
  }

  public CIFFAndDurationVector(CIFFAndDurationVector other) : this(CAFFParserPINVOKE.new_CIFFAndDurationVector__SWIG_1(CIFFAndDurationVector.getCPtr(other)), true) {
    if (CAFFParserPINVOKE.SWIGPendingException.Pending) throw CAFFParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public CIFFAndDurationVector(int capacity) : this(CAFFParserPINVOKE.new_CIFFAndDurationVector__SWIG_2(capacity), true) {
    if (CAFFParserPINVOKE.SWIGPendingException.Pending) throw CAFFParserPINVOKE.SWIGPendingException.Retrieve();
  }

  private CIFFAndDuration getitemcopy(int index) {
    CIFFAndDuration ret = new CIFFAndDuration(CAFFParserPINVOKE.CIFFAndDurationVector_getitemcopy(swigCPtr, index), true);
    if (CAFFParserPINVOKE.SWIGPendingException.Pending) throw CAFFParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private CIFFAndDuration getitem(int index) {
    CIFFAndDuration ret = new CIFFAndDuration(CAFFParserPINVOKE.CIFFAndDurationVector_getitem(swigCPtr, index), false);
    if (CAFFParserPINVOKE.SWIGPendingException.Pending) throw CAFFParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, CIFFAndDuration val) {
    CAFFParserPINVOKE.CIFFAndDurationVector_setitem(swigCPtr, index, CIFFAndDuration.getCPtr(val));
    if (CAFFParserPINVOKE.SWIGPendingException.Pending) throw CAFFParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(CIFFAndDurationVector values) {
    CAFFParserPINVOKE.CIFFAndDurationVector_AddRange(swigCPtr, CIFFAndDurationVector.getCPtr(values));
    if (CAFFParserPINVOKE.SWIGPendingException.Pending) throw CAFFParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public CIFFAndDurationVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = CAFFParserPINVOKE.CIFFAndDurationVector_GetRange(swigCPtr, index, count);
    CIFFAndDurationVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new CIFFAndDurationVector(cPtr, true);
    if (CAFFParserPINVOKE.SWIGPendingException.Pending) throw CAFFParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, CIFFAndDuration x) {
    CAFFParserPINVOKE.CIFFAndDurationVector_Insert(swigCPtr, index, CIFFAndDuration.getCPtr(x));
    if (CAFFParserPINVOKE.SWIGPendingException.Pending) throw CAFFParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, CIFFAndDurationVector values) {
    CAFFParserPINVOKE.CIFFAndDurationVector_InsertRange(swigCPtr, index, CIFFAndDurationVector.getCPtr(values));
    if (CAFFParserPINVOKE.SWIGPendingException.Pending) throw CAFFParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    CAFFParserPINVOKE.CIFFAndDurationVector_RemoveAt(swigCPtr, index);
    if (CAFFParserPINVOKE.SWIGPendingException.Pending) throw CAFFParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    CAFFParserPINVOKE.CIFFAndDurationVector_RemoveRange(swigCPtr, index, count);
    if (CAFFParserPINVOKE.SWIGPendingException.Pending) throw CAFFParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public static CIFFAndDurationVector Repeat(CIFFAndDuration value, int count) {
    global::System.IntPtr cPtr = CAFFParserPINVOKE.CIFFAndDurationVector_Repeat(CIFFAndDuration.getCPtr(value), count);
    CIFFAndDurationVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new CIFFAndDurationVector(cPtr, true);
    if (CAFFParserPINVOKE.SWIGPendingException.Pending) throw CAFFParserPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    CAFFParserPINVOKE.CIFFAndDurationVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    CAFFParserPINVOKE.CIFFAndDurationVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (CAFFParserPINVOKE.SWIGPendingException.Pending) throw CAFFParserPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, CIFFAndDurationVector values) {
    CAFFParserPINVOKE.CIFFAndDurationVector_SetRange(swigCPtr, index, CIFFAndDurationVector.getCPtr(values));
    if (CAFFParserPINVOKE.SWIGPendingException.Pending) throw CAFFParserPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
