//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Backend.CAFFParser {

public class DateTime : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DateTime(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DateTime obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DateTime obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DateTime() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CAFFParserPINVOKE.delete_DateTime(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ushort year {
    set {
      CAFFParserPINVOKE.DateTime_year_set(swigCPtr, value);
    } 
    get {
      ushort ret = CAFFParserPINVOKE.DateTime_year_get(swigCPtr);
      return ret;
    } 
  }

  public byte month {
    set {
      CAFFParserPINVOKE.DateTime_month_set(swigCPtr, value);
    } 
    get {
      byte ret = CAFFParserPINVOKE.DateTime_month_get(swigCPtr);
      return ret;
    } 
  }

  public byte day {
    set {
      CAFFParserPINVOKE.DateTime_day_set(swigCPtr, value);
    } 
    get {
      byte ret = CAFFParserPINVOKE.DateTime_day_get(swigCPtr);
      return ret;
    } 
  }

  public byte hour {
    set {
      CAFFParserPINVOKE.DateTime_hour_set(swigCPtr, value);
    } 
    get {
      byte ret = CAFFParserPINVOKE.DateTime_hour_get(swigCPtr);
      return ret;
    } 
  }

  public byte minute {
    set {
      CAFFParserPINVOKE.DateTime_minute_set(swigCPtr, value);
    } 
    get {
      byte ret = CAFFParserPINVOKE.DateTime_minute_get(swigCPtr);
      return ret;
    } 
  }

  public DateTime() : this(CAFFParserPINVOKE.new_DateTime(), true) {
  }

}

}
