//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Backend.CAFFParser {

public enum Endianess {
  BIG_ENDIAN_MODE = 0,
  LITTLE_ENDIAN_MODE = 1
}

}
