/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.hagyma.api.model

import com.example.hagyma.api.model.AuthRoles

import com.squareup.moshi.Json

/**
 * 
 *
 * @param role 
 * @param userName 
 */


data class AuthUser (

    @Json(name = "role")
    val role: AuthRoles? = null,

    @Json(name = "userName")
    val userName: kotlin.String? = null

)

