/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.hagyma.api.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param preview 
 * @param title 
 */


data class CaffItem (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "preview")
    val preview: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String

)

