/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.hagyma.api.model

import com.example.hagyma.api.model.Comment

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param preview 
 * @param title 
 * @param comments 
 * @param description 
 * @param uploadTime 
 */


data class CaffDetails (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "preview")
    val preview: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "comments")
    val comments: kotlin.collections.List<Comment>? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "uploadTime")
    val uploadTime: java.time.OffsetDateTime? = null

)

