/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.hagyma.api.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param content 
 */


data class CommentRequest (

    @Json(name = "content")
    val content: kotlin.String

)

