/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.hagyma.api.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param email 
 * @param password 
 * @param username 
 */


data class RegisterRequest (

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "username")
    val username: kotlin.String

)

