/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.hagyma.api.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param currentPassword 
 * @param newPassword 
 */


data class UserChangeRequest (

    @Json(name = "currentPassword")
    val currentPassword: kotlin.String,

    @Json(name = "newPassword")
    val newPassword: kotlin.String

)

