/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.hagyma.api.model


import com.squareup.moshi.Json
import java.util.*

/**
 * 
 *
 * @param email 
 * @param id 
 * @param name 
 */


data class User(

    @Json(name = "email")
    val email: String,

    @Json(name = "id")
    val id: UUID,

    @Json(name = "name")
    val name: String

)

